### ISSUE TITLE
Unable to clone via SouceTree

### ISSUE THREAD

**Issue by nobuyukinyuu** [Regal-Internet-Brothers/regal-modules#1]
hi,

by default, SourceTree gives a recursive clone command similar to the one in your installation instructions.  However, this repo has no submapping for the publicdatastream repo, attempts to clone the repo will fail.  I don't know if there is a workaround on the commandline, but it's a moot point anyway since accessing the git 'shell' from SourceTree is impossible until you're able to clone the project first.

Proposed workaround:  Delete the link to submodule 'publicdatastream' for this branch, or make it map to somewhere public...

**Comment by ImmutableOctet** [comment]
The latest commit should fix this. I forgot it didn't properly delete it on the remote repository, thanks for the tip. For reference, 'publicdatastream' is now a part of 'ioutil'.
